# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_name', models.CharField(max_length=15)),
                ('admin_password', models.CharField(max_length=25)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(auto_created=True)),
                ('player_first_name', models.CharField(max_length=40)),
                ('player_last_name', models.CharField(max_length=40)),
                ('player_age', models.IntegerField()),
                ('player_country', models.CharField(choices=[('IND', 'IND'), ('SA', 'SA'), ('AUS', 'AUS'), ('ENG', 'ENG'), ('WI', 'WI'), ('NZ', 'NZ'), ('PAK', 'PAK'), ('SL', 'SL'), ('BAN', 'BAN')], max_length=10)),
                ('player_type', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL'), ('WK', 'WK'), ('ALL', 'ALL')], max_length=10)),
                ('player_price', models.IntegerField()),
                ('player_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField()),
                ('player_is_powerplayer', models.BooleanField(default=False)),
                ('player_score_belonging_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPortal.Player')),
            ],
        ),
    ]
